build.gradle.kts
src/main/kotlin/sparta/nbcamp/wachu/infra/swagger/SwaggerConfig.kt

> 간단 요약
Swagger와 Swagger config 추가
Swagger와 Swagger config 추가
---
closes: #6

:sparkles: Swagger 추가

---

src/main/kotlin/sparta/nbcamp/wachu/infra/security/SecurityConfig.kt

> 간단 요약
기초적인 SecurityConfig 설정을 진행했습니다.
auth prefix api
swagger
h2 console
에 대한 예외처리
`MockMvc` 로 조회가 되는지 테스트 코드를 만들 수 있어보이는데
현재 테스트 의존성이 없어서 의존성 설정부터 해야겠습니다
---
closes: #15

:sparkles: SecurityConfig 추가

---

build.gradle.kts
src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SignUpRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/UserRole.kt
src/main/kotlin/sparta/nbcamp/wachu/security/jwt/JwtAuthenticationFilter.kt
src/main/kotlin/sparta/nbcamp/wachu/security/jwt/JwtAuthenticationToken.kt
src/main/kotlin/sparta/nbcamp/wachu/security/jwt/JwtTokenManager.kt
src/main/kotlin/sparta/nbcamp/wachu/security/jwt/UserPrincipal.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/security/JwtTest.kt

> jwt 토큰 생성, 검증, 필터 구현 및 테스트 코드 작성
아직 스웨거로 테스트 미진행
> 토큰 클레임에  memberId,  email,  nickname, userRole 정보담겨져 있음
userPrincipal에         memberId, email ,nickname userRole 담겨져 있음
토큰에 정보가 제대로 들어왔는지에 대한 테스트 코드 작성함
토큰의 만료시간에 대한 테스트 코드는 작성하지 않음
> 토큰안에 email,nickname 등 삭제 여부 
---
closes: #5

✨ JWT Filter 추가 

---

src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/controller/v1/PairingController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/dto/v1/PairingRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/dto/v1/PairingResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/model/v1/Pairing.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingJpaRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt

> 페어링 도메인 기본
> 컨트롤러, 서비스, 리포지토리, 엔티티, 디티오
> 1. PairingJpaRepository 에는 아직 아무 펑션 안넣었습니다. 괜찮은가요?
> 2. 컨트롤러 createPairing 펑션에는 PathVariable 없는것 맞지요?
---
closes: #2

:sparkles: 페어링 도메인 기본구조

---

src/main/kotlin/sparta/nbcamp/wachu/exception/AccessDeniedException.kt
src/main/kotlin/sparta/nbcamp/wachu/exception/GlobalExceptionHandler.kt
src/main/kotlin/sparta/nbcamp/wachu/exception/ModelNotFoundException.kt
src/main/kotlin/sparta/nbcamp/wachu/exception/dto/ErrorDto.kt

> 간단 요약
GlobalExceptionHandler와 주로 사용할 것 같은 친숙한 Exception 추가
GlobalExceptionHandler와 주로 사용할 것 같은 친숙한 Exception 추가
더 추가하고 싶은 Exception 있으면 리뷰에 남겨주세요
---
closes: #24

:sparkles: Global exception handler 추가

---

src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/controller/v1/PairingController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/service/v1/PairingServiceImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/controller/v1/ReviewController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/model/v1/Review.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewJpaRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt

> 리뷰 도메인 기본
> 컨트롤러, 서비스, 리포지토리, 엔티티, 디티오
> 리뷰, 페어링 도메인 공통사항: 컨트롤러 경로변수(review_id) 와 함수 파라미터(id) 불일치하대요..ㅠㅠ 어떻게 수정할까요?
---
closes: #4

:sparkles: 리뷰 도메인 기본구조

---

src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SignUpRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/SignUpResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/dto/TokenResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberJpaRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtTokenManager.kt

> 로그인, 회원가입 구현
> 기본적인 CRUD 구현
> 
---
closes: #7

:art: 로그인,회원가입 구현

---

src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/controller/WineController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/RecommendWineRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/WineResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/entity/Type.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/entity/Wine.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/entity/WineType.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/repository/WineJpaRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/repository/WineRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/repository/WineRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineServiceImpl.kt

> 간단한 와인 CRUD 구조 작성
> Controller,Service,Entity,Repository,Dto 구조 생성 
---
closes: #3

:sparkles: Feat/3 wine domain structure

---

src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtAuthenticationFilter.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtTokenManager.kt

> 간단 요약
> 
해당 부분 오류 발생하여 memberId를 claim에서 subject로 저장하는 것으로 수정하였습니다
---
closes: #35

:ambulance:  jwt 수정

---

build.gradle.kts

> 간단 요약
QueryDSL 추가
QueryDSL 쓰기 전에 compileKotlin 으로 QClass 생성하는거 까먹지 마세영
QueryDSL 추가
---
closes: #43

:heavy_plus_sign: QueryDSL 추가

---

src/main/kotlin/sparta/nbcamp/wachu/domain/review/controller/v1/ReviewController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/model/v1/Review.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/pairing/service/PairingServiceTest.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/controller/ReviewControllerTest.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/repository/ReviewTestRepositoryImpl.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/service/ReviewServiceTest.kt

> 리뷰 crud
> 리뷰 crud 추가
> 별점 검증 로직 일단 재원님이 이륙허가
---
closes: #10

:sparkles: 리뷰 도메인 crud 추가

---

.gitignore

> 간단 요약
Ignore 수정
Ignore 수정
---
closes: #이슈번호

:see_no_evil: Ignore 수정

---

src/main/kotlin/sparta/nbcamp/wachu/domain/review/controller/v1/ReviewController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewQueryDslRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/pairing/service/PairingServiceTest.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/repository/ReviewTestRepositoryImpl.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/service/ReviewServiceTest.kt

> 리뷰 목록조회를 queryDSL 페이지네이션 함
> 해당펑션 서비스 및 컨트롤러 수정 + queryDSL용 리포지토리 생성 및 적용
> 페어링과 리뷰 서비스 테스트코드를
리스트조회 -> 페이지조회 반영해서 수정햇습니다.
각 getPage펑션 리뷰 부탁드립니다.
---
closes: #50

:sparkles: 리뷰 목록조회 queryDSL 페이지네이션

---

LICENSE

> 간단 요약
MIT LICENSE 추가입니다.
보통 라이브러리에서 제일 많이 쓰는 라이센스인데 대충 저작권이 우리에게 있다는 뜻입니다
FE에서 추가하는 김에 여기도 추가해둡니다
Mit License 추가

:memo: Create LICENSE

---

src/main/kotlin/sparta/nbcamp/wachu/infra/security/WebConfig.kt

> 간단 요약
CORS 허용을 위한 WebConfig 추가
---
closes: #70

:wrench: CORS 허용을 위한 WebConfig 추가

---

src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/model/v1/Review.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewQueryDslRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/repository/ReviewTestRepositoryImpl.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/service/ReviewServiceTest.kt

> 리뷰와 와인을 Fetchjoin
> JPA 연관관계 설정 (단방향 @ManyToOne 권장)
QueryDSL Fetch join 설정
성능비교는 이슈분리됨  -> https://github.com/spartaKotlinTeamSober/wachu_server/issues/68
테스트 코드 작성
> 
---
closes: #39

:sparkles: 리뷰 Fetchjoin

---

src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt

> 간단 요약
멍청하게 빼먹은 콤마 추가
멍청하게 빼먹은 콤마 추가

:ambulance: comma hotfix

---

build.gradle.kts
src/main/kotlin/sparta/nbcamp/wachu/infra/security/SecurityConfig.kt

:recycle: H2 -> RDS MySQL 마이그레이션

---

src/main/kotlin/sparta/nbcamp/wachu/domain/member/emailcode/service/CodeService.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/openai/service/WineEmbeddingService.kt
src/test/kotlin/sparta/nbcamp/wachu/WachuApplicationTests.kt

> 간단 요약
이메일 환경변수 yml로 통합
@SpringBootTest 재활성화
와인 추천 너무 느려서 임시로 제한
---
closes: #90

:bug: 배포중 발견한 문제 수정

---

build.gradle.kts
src/test/kotlin/sparta/nbcamp/wachu/domain/testH2db/H2DatabaseConnectionTest.kt
src/test/resources/application-test.yml

> 테스트용 h2(임베디드모드) 적용
> 빌드그래들 의존성 + 야믈 + 테스트코드
> 1. 연결 확인용 테스트코드 내용 맞는가요? (통과는 O)
> 2. 문제는 http://localhost:8080/h2-console 화이트라벨 (해결필요..)
---
closes: #97

:sparkles: 테스트용 h2 분리

---

src/main/kotlin/sparta/nbcamp/wachu/domain/review/controller/v1/ReviewController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewMultiMediaResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/dto/v1/ReviewResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewMultiMediaJpaRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewMultiMediaRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewMultiMediaRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/security/jwt/JwtAuthenticationFilter.kt

> 간단 요약
리뷰 생성에 따로 존재하던 API를 통합으로 관리하게 수정
리뷰 생성시 멀티 미디어 한번에 처리함
전체 조회를 제외한 ReviewResponse에 멀티 미디어를 포함함
---
closes: #100

:sparkles: 리뷰 멀티미디어 response 추가 / 수정

---

.github/workflows/CD.yml
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/WineResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineImageGetter.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/batches/s3directory/S3DirectoryBatchJob.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/KakaoOAuth2LoginClient.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/security/oauth/NaverOAuth2LoginClient.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/pairing/service/PairingServiceTest.kt
src/test/kotlin/sparta/nbcamp/wachu/domain/review/service/ReviewServiceTest.kt

> 와인 이미지 매칭 로직 변경
> 와인 이미지 매칭 로직 변경
랜덤이미지->id%imageCnt
---
closes: #114

♻️ #114/와인 이미지 매칭 로직 수정

---

src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt

> 간단 요약
`@RequestBody`랑 `@RequestPart`랑 같이 작성돼서 Body를 못받음
`@RequestPart`로 수정
---
closes: #116

:bug: 회원가입 Request 수정

---

src/main/kotlin/sparta/nbcamp/wachu/domain/member/controller/MemberController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/entity/Member.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/repository/MemberRepositoryImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/member/service/MemberServiceImpl.kt

> 간단 요약
개인정보 처리 관련 멤버 수정
개인정보 약관은 FE에서 작성했습니다
---
closes: #113

:sparkles: 개인정보 처리 관련 멤버 수정

---

src/main/kotlin/sparta/nbcamp/wachu/domain/review/service/v1/ReviewServiceImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/controller/WineController.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/RecommendWineRequest.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/dto/WineRecommendResponse.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/entity/Wine.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineService.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/service/WineServiceImpl.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/openai/common/utils/WineEmbeddingUtility.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/openai/dto/WineEmbeddingData.kt
src/main/kotlin/sparta/nbcamp/wachu/infra/openai/service/WineEmbeddingService.kt

> 간단 요약
와인 추천 로직에 가중치가 들어가고 유사도를 같이 반환함
weight 추가
similarity 추가
코드 구조가 개떡같습니다 DTO가 여행을 너무 많이 다닙니다
---
closes: #30, #12

:sparkles: 와인 추천에 가중치 및 유사도 포함

---

src/main/kotlin/sparta/nbcamp/wachu/domain/common/QueryDslUtils.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/pairing/repository/v1/PairingQueryDslRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/model/v1/Review.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/review/repository/v1/ReviewQueryDslRepository.kt
src/main/kotlin/sparta/nbcamp/wachu/domain/wine/repository/WineQueryDslRepositoryImpl.kt

> 간단 요약
FE에 맞춰서 API 양식 수정 
review description text로 지정
페어링 / 리뷰 조회에 sort 설정 가능
---
closes: #111

:sparkles: FE에 맞춰서 API 양식 수정 
